# Generated by Django 5.1 on 2024-09-16 13:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0002_alter_cliente_data_nascimento_alter_cliente_endereco_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cliente',
            name='escolaridade',
            field=models.CharField(default='a definir', max_length=10),
            preserve_default=False,
        ),
    ]
