# Generated by Django 5.1.1 on 2024-09-23 13:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vendas', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entrega',
            name='data_entrega',
            field=models.DateTimeField(max_length=100),
        ),
        migrations.AlterField(
            model_name='entrega',
            name='data_envio',
            field=models.DateTimeField(max_length=100),
        ),
    ]
