# Generated by Django 5.1.3 on 2024-12-05 13:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cadastro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=150)),
                ('idade', models.IntegerField()),
                ('CPF', models.IntegerField()),
                ('email', models.EmailField(max_length=254)),
                ('telefone', models.IntegerField()),
                ('data_cadastro', models.DateField(max_length=10)),
            ],
        ),
    ]
