# Generated by Django 5.1.3 on 2024-12-13 13:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cadastros', '0003_documento_remove_cadastro_cpf_cadastro_documento'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Documento',
            new_name='Tipo_quarto',
        ),
        migrations.RenameField(
            model_name='cadastro',
            old_name='documento',
            new_name='tipo_quarto',
        ),
        migrations.AddField(
            model_name='cadastro',
            name='cpf',
            field=models.CharField(default='a definir', max_length=11),
            preserve_default=False,
        ),
    ]
