# Generated by Django 5.1.3 on 2025-02-03 18:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cadastros', '0004_rename_documento_tipo_quarto_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cadastro',
            name='tipo_quarto',
        ),
    ]
