# Generated by Django 5.1.3 on 2025-02-06 17:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cadastros', '0005_remove_cadastro_tipo_quarto'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cadastro',
            name='forma_pegamento',
        ),
        migrations.DeleteModel(
            name='Tipo_quarto',
        ),
        migrations.RenameField(
            model_name='cadastro',
            old_name='nome',
            new_name='cidade',
        ),
        migrations.RemoveField(
            model_name='cadastro',
            name='cpf',
        ),
        migrations.RemoveField(
            model_name='cadastro',
            name='email',
        ),
        migrations.RemoveField(
            model_name='cadastro',
            name='quantidade_pessoas',
        ),
        migrations.AddField(
            model_name='cadastro',
            name='documento',
            field=models.CharField(default='', max_length=150),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='cadastro',
            name='endereco',
            field=models.CharField(default='', max_length=1000),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='cadastro',
            name='estado',
            field=models.CharField(default='', max_length=150),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='cadastro',
            name='nome_completo',
            field=models.CharField(default='', max_length=150),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='cadastro',
            name='tipo_documento',
            field=models.CharField(choices=[('cpf', 'CPF'), ('rg', 'RG'), ('cn', 'CN'), ('passaporte', 'PASSAPORTE'), ('cie', 'CIE'), ('ci', 'CI'), ('dni', 'DNI')], default='cpf', max_length=150),
        ),
        migrations.DeleteModel(
            name='Forma_pagamento',
        ),
    ]
