# Generated by Django 5.1.3 on 2025-02-08 10:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cadastros', '0006_remove_cadastro_forma_pegamento_delete_tipo_quarto_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cadastro',
            name='tipo_quarto',
            field=models.CharField(choices=[('quarto com uma cama de solteiro', 'Quarto com uma cama de solteiro'), ('quarto com duas camas de solteiro', 'Quarto com duas camas de solteiro'), ('quarto com uma cama de casal', 'Quarto com uma cama de casal'), ('quarto com duas cama de casal', 'Quarto com duas cama de casal'), ('quarto com uma cama de casal e uma de solteiro', 'Quarto com uma cama de casal e uma de solteiro'), ('quarto com duas cama de casal e duas de solteiro', 'Quarto com duas cama de casal e duas de solteiro')], default='quarto com uma cama de casal', max_length=150),
        ),
    ]
