numero = int(input('Digite um numero: '))

#print(f'{numero} x 0 = {numero * 0}')
#print(f'{numero} x 1 = {numero * 1}')
#print(f'{numero} x 2 = {numero * 2}')
#print(f'{numero} x 3 = {numero * 3}')
#print(f'{numero} x 4 = {numero * 4}')
#print(f'{numero} x 5 = {numero * 5}')
#print(f'{numero} x 6 = {numero * 6}')
#print(f'{numero} x 7 = {numero * 7}')
#print(f'{numero} x 8 = {numero * 8}')
#print(f'{numero} x 9 = {numero * 9}')


print(str(numero) + 'x0 = ' + str(numero *0))
print(str(numero) + 'x1 = ' + str(numero *1))
print(str(numero) + 'x2 = ' + str(numero *2))
print(str(numero) + 'x3 = ' + str(numero *3))
print(str(numero) + 'x4 = ' + str(numero *4)) 
print(str(numero) + 'x5 = ' + str(numero *5))
print(str(numero) + 'x6 = ' + str(numero *6))
print(str(numero) + 'x7 = ' + str(numero *7))
print(str(numero) + 'x8 = ' + str(numero *8))
print(str(numero) + 'x9 = ' + str(numero *9))