# Generated by Django 5.1.3 on 2025-02-03 18:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('feedbacks', '0002_contato'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Contato',
        ),
        migrations.RemoveField(
            model_name='feedback',
            name='sugestao',
        ),
    ]
