# Generated by Django 5.1.3 on 2024-12-05 13:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Aluguelcarros',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_aluguel', models.DateField(max_length=10)),
                ('pessoa', models.CharField(max_length=100)),
                ('veiculo', models.CharField(max_length=100)),
                ('ativo', models.BooleanField(default=True)),
                ('motorista', models.BooleanField(default=True)),
                ('taxa', models.DecimalField(decimal_places=4, max_digits=8)),
            ],
        ),
    ]
