# Generated by Django 5.1.3 on 2024-12-05 13:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('aluguelcarros', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='aluguelcarros',
            name='ativo',
        ),
        migrations.RemoveField(
            model_name='aluguelcarros',
            name='taxa',
        ),
    ]
