# Generated by Django 5.1.3 on 2024-12-13 13:12

import django.db.models.deletion
from django.db import migrations, models
from datetime import datetime

class Migration(migrations.Migration):

    dependencies = [
        ('aluguelcarros', '0002_remove_aluguelcarros_ativo_remove_aluguelcarros_taxa'),
    ]

    operations = [
        migrations.CreateModel(
            name='Forma_pagamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Tipo_carro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
            ],
        ),
        migrations.RenameField(
            model_name='aluguelcarros',
            old_name='pessoa',
            new_name='nome',
        ),
        migrations.RemoveField(
            model_name='aluguelcarros',
            name='data_aluguel',
        ),
        migrations.RemoveField(
            model_name='aluguelcarros',
            name='veiculo',
        ),
        migrations.AddField(
            model_name='aluguelcarros',
            name='cpf',
            field=models.CharField(default='00000', max_length=11),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='aluguelcarros',
            name='fim_reserva',
            field=models.DateField(auto_now_add=True, default=datetime.now()),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='aluguelcarros',
            name='inicio_reserva',
            field=models.DateField(auto_now_add=True, default=datetime.now()),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='aluguelcarros',
            name='forma_pagamento',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='aluguelcarros.forma_pagamento'),
        ),
        migrations.AddField(
            model_name='aluguelcarros',
            name='tipo_carro',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='aluguelcarros.tipo_carro'),
        ),
    ]
