# Generated by Django 5.1.4 on 2025-01-11 13:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aluguelcarros', '0004_carros'),
    ]

    operations = [
        migrations.AddField(
            model_name='carros',
            name='foto',
            field=models.CharField(default='', max_length=400),
            preserve_default=False,
        ),
    ]
