# Generated by Django 5.1.4 on 2025-01-11 13:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aluguelcarros', '0005_carros_foto'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='aluguelcarros',
            name='tipo_carro',
        ),
        migrations.AddField(
            model_name='aluguelcarros',
            name='carro',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='aluguelcarros.carros'),
        ),
    ]
