# Generated by Django 5.1.3 on 2025-02-03 18:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aluguelcarros', '0006_remove_aluguelcarros_tipo_carro_aluguelcarros_carro'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='carros',
            name='foto',
        ),
        migrations.AddField(
            model_name='carros',
            name='imagem',
            field=models.ImageField(default=' ', max_length=1000, upload_to=''),
            preserve_default=False,
        ),
    ]
