# Generated by Django 5.1.3 on 2025-02-03 18:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aluguelcarros', '0008_alter_carros_imagem'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carros',
            name='imagem',
            field=models.ImageField(blank=True, null=True, upload_to='Carros'),
        ),
    ]
