# Generated by Django 5.1.3 on 2025-02-06 17:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aluguelcarros', '0009_alter_carros_imagem'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aluguelcarros',
            name='forma_pagamento',
            field=models.CharField(default='', max_length=150),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='Tipo_carro',
        ),
        migrations.RemoveField(
            model_name='aluguelcarros',
            name='carro',
        ),
        migrations.RemoveField(
            model_name='aluguelcarros',
            name='motorista',
        ),
        migrations.DeleteModel(
            name='Forma_pagamento',
        ),
    ]
