# Generated by Django 5.1.4 on 2025-02-06 20:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aluguelcarros', '0010_alter_aluguelcarros_forma_pagamento_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='aluguelcarros',
            name='carro',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='aluguelcarros.carros'),
        ),
    ]
