# Generated by Django 5.1.4 on 2025-02-06 20:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aluguelcarros', '0011_aluguelcarros_carro'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aluguelcarros',
            name='fim_reserva',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='aluguelcarros',
            name='inicio_reserva',
            field=models.DateField(help_text='Data de inicio da reserva'),
        ),
    ]
