# Generated by Django 5.1.1 on 2024-10-11 13:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='bio',
            field=models.TextField(default='valor padrao'),
        ),
    ]
