# Generated by Django 5.1.1 on 2024-10-11 13:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_book_bio'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='bio',
            field=models.TextField(),
        ),
    ]
