# Generated by Django 5.1.1 on 2024-10-03 11:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contrato',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imovel', models.CharField(max_length=100)),
                ('data_inicio', models.DateField()),
                ('data_fim', models.DateField()),
                ('nome_cliente', models.CharField(max_length=100)),
                ('ativo', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='ImovelAluguel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('alugar', models.CharField(max_length=100)),
                ('preco_mes', models.DecimalField(decimal_places=2, max_digits=8)),
                ('descricacao', models.TextField()),
                ('endereco', models.CharField(max_length=100)),
                ('disponibilidade_inicio', models.DateField()),
                ('disponibilidade_fim', models.DateField()),
                ('ativo', models.BooleanField(default=True)),
            ],
        ),
    ]
