# Generated by Django 5.1.1 on 2024-10-03 11:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alugueis', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='imovelaluguel',
            name='foto_imovelaluguel',
            field=models.ImageField(blank=True, null=True, upload_to='alugueis'),
        ),
    ]
