# Generated by Django 5.1.1 on 2024-10-03 11:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vendas', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='reserva',
            name='descricao',
            field=models.TextField(default='a defini'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='venda',
            name='ativo',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='venda',
            name='descricacao',
            field=models.TextField(default='a defini'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='venda',
            name='data_venda',
            field=models.DateField(),
        ),
    ]
