# Generated by Django 5.1.1 on 2024-10-03 11:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vendas', '0002_reserva_descricao_venda_ativo_venda_descricacao_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='venda',
            name='foto_vendas',
            field=models.ImageField(blank=True, null=True, upload_to='vendas'),
        ),
    ]
